# Generated by Django 4.2.4 on 2023-09-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookamarks',
            field=models.ManyToManyField(through='myapp.Bookmark', to='myapp.post'),
        ),
    ]
