# Generated by Django 4.2.4 on 2023-09-19 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_bookamarks_user_bookmarks_alter_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subscriber', models.ForeignKey(db_column='subscriber_id', on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SubscriberItems',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='subscribers',
            field=models.ManyToManyField(related_name='follows', through='myapp.SubscriberItems', to=settings.AUTH_USER_MODEL),
        ),
    ]
