# Generated by Django 4.2.4 on 2023-09-19 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_subscriberitems_user_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriberitems',
            name='subscriber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='subscriberitems',
            name='follower',
            field=models.ForeignKey(db_column='follower_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items_following', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='following', through='myapp.SubscriberItems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriberitems',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='sub_items_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
